FIX: workflow

diff --git a/.github/workflows/terraform.main.yml b/.github/workflows/terraform.main.yml
--- a/.github/workflows/terraform.main.yml
+++ b/.github/workflows/terraform.main.yml
@@ -1,4 +1,4 @@
-name: Terraform Plan
+name: Terraform Plan and Apply
 
 on:
   push:
@@ -13,7 +13,7 @@ on:
       - 'main/**'
 
 jobs:
-  terraform-plan:
+  terraform:
     runs-on: ubuntu-latest
     permissions:
       id-token: write
@@ -35,8 +35,40 @@ jobs:
       with:
         terraform_version: 1.9.8
 
+    - name: Set Workspace Name
+      run: |
+        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+          echo "TERRAFORM_WORKSPACE=${{ github.base_ref }}" >> $GITHUB_ENV
+        else
+          echo "TERRAFORM_WORKSPACE=${{ github.head_ref }}" >> $GITHUB_ENV
+        fi
+
     - name: Terraform Init
       run: terraform init
+      working-directory: ./main
+
+    - name: Verify and Prepare Terraform Workspace
+      run: |
+        echo "Current TERRAFORM_WORKSPACE: $TERRAFORM_WORKSPACE"
+        
+        # Check if the workspace exists
+        if terraform workspace list 2>&1 | grep -q "$TERRAFORM_WORKSPACE"; then
+          echo "Workspace $TERRAFORM_WORKSPACE exists. It will be used automatically."
+        else
+          echo "Workspace $TERRAFORM_WORKSPACE does not exist. Creating it."
+          terraform workspace new $TERRAFORM_WORKSPACE
+        fi
+        
+        # Verify the current workspace
+        CURRENT_WORKSPACE=$(terraform workspace show)
+        echo "Current Terraform workspace: $CURRENT_WORKSPACE"
+        
+        if [ "$CURRENT_WORKSPACE" != "$TERRAFORM_WORKSPACE" ]; then
+          echo "Error: Current workspace ($CURRENT_WORKSPACE) does not match TERRAFORM_WORKSPACE ($TERRAFORM_WORKSPACE)"
+          exit 1
+        else
+          echo "Confirmed: Using workspace $TERRAFORM_WORKSPACE"
+        fi
       working-directory: ./main
 
     - name: Terraform Format Check
@@ -44,10 +76,10 @@ jobs:
       working-directory: ./main
 
     - name: Terraform Plan
-      run: terraform plan
+      run: terraform plan -no-color
       working-directory: ./main
-      env:
-        TF_VAR_github_token: "TEST"
-        # Add any necessary environment variables for your Terraform configuration
-        # For example:
-        # TF_VAR_example: ${{ secrets.TF_VAR_EXAMPLE }}
+
+    - name: Terraform Apply
+      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      run: terraform apply -auto-approve -no-color
+      working-directory: ./main
